# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4456734f660677e07ab1de7c836233ef8a0899d396ab3376b132329a9f2425f753dc1042cb38d7080e2957256918d80f9ef21f6dd9349cb73c0ceb5af6e91295

test:
  secret_key_base: 45d86c4acfb7a8193f2c2de1fc01d2b21485cab59da0ef6c3776da15577bef932d082cda6d37f304bdbea22e3d63c2bc8e48ef107ccf02907baf8c260166f972

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
